Add a very minimal adding machine
This project interprets a summation, e.g. `1 + 2 + 5`, and prints the
result.

The lexer tokenizes integers, ignores whitespace, and lets all other
characters pass through to the parser. The integer tokens have to be
cast as integers from the yytext global variable that stores the match.
The integer value will be automatically tied to the NUM token (the type
is set in the `%define api.value.typ` line in the bison file).

The noyywrap resolves the annoying error message:

```
bison -d adder.y
flex adder.l
gcc -o adder.out adder.tab.c lex.yy.c
/tmp/ccSJA0L9.o: In function `yylex':
lex.yy.c:(.text+0x444): undefined reference to `yywrap'
/tmp/ccSJA0L9.o: In function `input':
lex.yy.c:(.text+0xfe2): undefined reference to `yywrap'
collect2: error: ld returned 1 exit status
make: *** [Makefile:21: adder] Error 1
```

Bison is linked to Flex by inclusion of the `lex.yy.h` header file.
Specifically, bison needs the yylex() function. If you didn't want to
use Flex, you could roll your own yylex().

Flex requires the tokens declared in the Bison file, which are obtained
by including the bison header `adder.tab.h`.

If the `%left '+'` line is missing in the `adder.y` file, compilation
will yield the warning:

```
adder.y: warning: 1 shift/reduce conflict [-Wconflicts-sr]
```

This conflict arise in the rule

```
exp
  : NUM
  | exp '+' exp
```

The parser does not know which side of the '+' to reduce first. By
specifying `%left '+'`, you tell Bison to first reduce the left side for
this character.

Incidentally, for the '+' operator, left and right associativity leads
to the same result, but the parser doesn't know this. You can ignore the
warning; the output will be correct since bison by default reduces first
(left associative). If instead of '+', we called the operator '^', for
exponentiation, Bison would do exactly the same thing, but the results
would be incorrect: `4^3^2` will be interpreted as `(4^3)^2`.