Implement multiple YYSTYPE's and tree structure
A nested list can be stored as a two-way linked list. Each node points
left and right to elements at the same level. A node may contain hold a
concrete value or a pointer to a nested element.

Integrating this data structure required typing my tokens. Rather than
all having the type `char*`, I define the type as a union. Here is the
bison code:

```
%define api.value.type union

%token <char*> NAME
%token <int> NUM

%type <Node*> exp;
```

Bison automatically builds a union with the appropriate types defined
inside (which it acquires from the `%token <TYPE>` statements). The
generated code can be found in `nest.tab.h`:

```
union YYSTYPE
{
  Node* exp;
  char* NAME;
  int NUM;
};
```

For the most part, everything Just Works. I can access the typed values
in Bison with in exactly the same way as before (e.g. '$$ = $1').

In the Flex code, I just have to change yylval usage to store the
incoming values in the right union slot, e.g.

```
{num}   { sscanf(yytext, "%d", &yylval.NUM); return NUM;  }
{name}  { yylval.NAME = strdup(yytext); return NAME; }
```

Also note that groups, e.g. `exp`, now need to specify type if they are
asigned values (via `$$`).

Weirdly, the trickiest part of the change, by far, was getting bison to
see my `node.h` header. Initially, I wrote at the head of my nest.y file:

```
%{
\#include <stdio.h>
\#include "lex.yy.h"
\#include "node.h"
%}
```

and got the error:

```
bison -d nest.y
flex nest.l
gcc -o nest.out node.c nest.tab.c lex.yy.c
In file included from nest.l:2:0:
nest.tab.h:60:3: error: unknown type name ‘Node’
   Node* exp;
      ^~~~
      make: *** [Makefile:21: nest] Error 1
```

The type `Node*` was used in `nest.tab.h` within the union, but the
`node.h` header was included in the `nest.tab.c`. The material in the
prologue is just for Bison, it isn't exported to the header.

To export code to the header, you need to wrap it in a special bison
construct:

```
%code requires {
\#include "node.h"
}
```

Within the `nest.tab.c` source code, the 'requires' code block is
written after the top block. A bunch of innocuous looking macros are
defined between them. I do not know if this difference is ever
important.

RTFM for details, that's what finally saved my head(er).